### ISSUE TITLE
Crash on version 2024.131.0

### ISSUE THREAD

**Issue by R3dDiamond** [goodtrailer/soyokaze#170]
crashes when joining a map. 
here are the first few lines of the error:

[error]: An unhandled error has occurred.
[error]: System.MissingMethodException: Method not found: 'osu.Framework.Bindables.Bindable`1<Double> osu.Framework.Graphics.UserInterface.CircularProgress.get_Current()'.
[error]: at osu.Game.Rulesets.Soyokaze.Skinning.SkinnableHoldProgress..ctor()
[error]: at osu.Game.Rulesets.Soyokaze.Objects.Drawables.DrawableHold.load()
[error]: at osu.Game.Rulesets.Soyokaze.Objects.Drawables.DrawableHold.<>c.<RegisterForDependencyActivation>b__25_0(Object t, IReadOnlyDependencyContainer d)

**Comment by R3dDiamond** [comment]
![afbeelding](https://github.com/goodtrailer/soyokaze/assets/108217181/ee5482c8-4308-4b0b-961b-1124e2577c8d)
just loads forever

**Comment by goodtrailer** [comment]
Thanks for the notification! Seems the auto-updater stopped working because osu! moved to a new .NET version, which I had no idea about. Should be fixed with latest release (#171).
