### ISSUE TITLE
Add input options

### ISSUE THREAD

**Issue by SolsticeSpectrum** [goodtrailer/soyokaze#175]
I would like to play this on WSAD + arrows rather than WSAD + IJKL. I hate this in osu!mania too, I'm a big guy and putting my hands so close together is very uncomfortable.

**Comment by goodtrailer** [comment]
this should already exist, it's just a little hard to find (it's in the same menu for keybinds as all the other game modes). is this showing for you?

![image](https://github.com/goodtrailer/soyokaze/assets/46171121/23d223e4-8f69-4858-8405-ad990ea56b7e)
