### ISSUE TITLE
osu!lazer gives error when game opens

### ISSUE THREAD

**Issue by ThatTechGuy2008** [goodtrailer/soyokaze#204]
When attempting to place the ruleset in the ruleset folder and open the game, the following error occurs: 
<img width="179" alt="osu! 12_9_2024 1_39_59 PM" src="https://github.com/user-attachments/assets/4dad1b7c-7a8b-4b68-be6b-efe715aa801a">

**Comment by goodtrailer** [comment]
Fixed in [latest release](https://github.com/goodtrailer/soyokaze/releases/tag/2024.1212.0)

Thanks for reporting! :)
