### ISSUE TITLE
Enable Hold Mode by default on specially crafted map?

### ISSUE THREAD

**Issue by rorre** [goodtrailer/soyokaze#35]
Might be useful if there are maps out there that is made specifically for this ruleset. (*cough cough* [like my map here](https://osu.ppy.sh/beatmapsets/1610681#osu/3288601) *cough cough*)

Maybe checking the map's tags if there is somethin like "soyokaze", similar to how [Rush! does](https://github.com/Beamographic/rush/blob/master/osu.Game.Rulesets.Rush/Beatmaps/RushBeatmapConverter.cs#L25-L28).

Regardless, cool stuff :)

**Comment by goodtrailer** [comment]
Resolved in release [`2021.1111.0`](https://github.com/goodtrailer/soyokaze/releases/tag/2021.1111.0) in commit fa22ce1744d827651cf5838c0e88fddfa874d9f5.
Holds are now generated by default on all maps.
