### ISSUE TITLE
Visual Settings not respected when starting a new beatmap

### ISSUE THREAD

**Issue by LeNitrous** [goodtrailer/soyokaze#6]
Awesome recreation! I'm enjoying it so far. Though what onlyirks me so far is the kiai visualizer and input display not respecting the setting everytime I start a new beatmap. A quick fix to this is setting the last argument of `BindValueChanged` to `true` so the action on the former argument should run at least once.

https://github.com/goodtrailer/soyokaze/blob/2e66415a742cfdb1b3a9ba51fc5dfa4686f3843d/osu.Game.Rulesets.Soyokaze/UI/SoyokazePlayfield.cs#L62
https://github.com/goodtrailer/soyokaze/blob/2e66415a742cfdb1b3a9ba51fc5dfa4686f3843d/osu.Game.Rulesets.Soyokaze/UI/SoyokazePlayfield.cs#L64

**Comment by goodtrailer** [comment]
Derp, thanks for notifying me about this. Should be fixed now.
