### ISSUE TITLE
Running into an issue while trying to create tests for ruleset

### ISSUE THREAD

**Issue by zmshah** [goodtrailer/soyokaze#9]
I was trying to add tests to this ruleset similar to some of the other rulesets. Added a visual test runner and testsceneosugame but running into an issue when trying to create the player test scene. This is the error osu.Framework.Allocation.DependencyNotRegisteredException: 'The type SoyokazePlayfield has a dependency on SoyokazeConfigManager, but the dependency is not registered.'

I believe the problem is with the load method in soyokazeplayfield. I tried passing true into the dependencyloader to see what happens which is how I came to this conclusion. I've attached the exception details as txt files as well as screenshots. Not really sure how to go forward with this.

p.s My group and I are currently trying to write tests for an opensource project as part of out Software testing class in college, and we thought that maybe we could try setting up soyokaze for tests in a similar way to other custom rulesets. Of course if you don't want us to do so with this project we will definitely stop. 
[Exception details 1.txt](https://github.com/goodtrailer/soyokaze/files/6446972/Exception.details.1.txt)
[Exception details 2.txt](https://github.com/goodtrailer/soyokaze/files/6446973/Exception.details.2.txt)
![Screenshot 2021-05-09 00 06 46](https://user-images.githubusercontent.com/64097486/117561407-2938cc00-b05c-11eb-8100-52676b2979f0.png)
![Screenshot 2021-05-09 00 07 26](https://user-images.githubusercontent.com/64097486/117561408-29d16280-b05c-11eb-9f89-9e48a248ed44.png)
![Screenshot 2021-05-09 00 19 27](https://user-images.githubusercontent.com/64097486/117561415-3bb30580-b05c-11eb-855a-6b2d0bdefa2d.png)

**Comment by goodtrailer** [comment]
f5fc4c5d74a0728cfbb41874d2fa2bad3b623be5 `Allow null config manager with dependency loader`
I'm hoping this commit fixed your issue. If not, then I'm not really sure how to fix it (the background dependency loader is honestly a bit magical to me). And feel free to do your project, this is open-source for a reason. I don't mind at all, and good luck. 👍

**Comment by zmshah** [comment]
Thank you so much. We'll try it out!!
